surveil:
  #build: .
  image: savoirfairelinux/surveil:0.4.4
  links:
   - mongo
   - influxdb
   - alignak
  ports:
   - "8080:8080"
  environment:
    PBR_VERSION: "PROD"
    #SURVEIL_AUTH_BACKEND: "keystone"
    #SURVEIL_KEYSTONE_HOST: "198.72.123.131"
    #SURVEIL_KEYSTONE_AUTH_PROTOCOL: "http"
    #SURVEIL_OS_USERNAME: "admin"
    #SURVEIL_OS_PASSWORD: "password"
    #SURVEIL_OS_TENANT_NAME: "admin"

rabbitconsummer:
  build: .
  links:
    - surveil
  environment:
    PBR_VERSION: "PROD"
    #SURVEIL_APIURL: "http://surveil:8080/v2"
    #SURVEIL_AUTH_URL: "http://surveil:8080/v2/auth"
    #SURVEIL_VERSION: "2_0"
    #RABBIT_HOST: "192.168.49.239"
    #RABBIT_PORT: 5672
    #QUEUE: " test"
    #RABBIT_USER: "admin"
    #RABBIT_PASSWORD: "admin"
    #OS_AUTH_URL: "auth-url"
    #OS_USERNAME "user"
    #OS_PASSWORD "password"

alignak:
  #build: tools/docker/alignak_container/
  image: savoirfairelinux/surveil-alignak:0.4.4
  links:
    - mongo
    - influxdb
  ports:
    - "7767:7767"

mongo:
  image: mongo
  ports:
   - "27017:27017"
  command:
      "mongod --smallfiles"
  volumes:
   - ./container-data/mongodb:/data/db

influxdb:
  image: savoirfairelinux/influxdb:0.9.0-rc30
  environment:
    PRE_CREATE_DB: "db"
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
   - ./container-data/influxdb:/data

grafana:
  image: savoirfairelinux/grafana:2.0.2
  environment:
    INFLUXDB_HOST: "influxdb"
    INFLUXDB_PORT: "8086"
    INFLUXDB_NAME: "db"
    INFLUXDB_USER: "root"
    INFLUXDB_PASS: "root"
  ports:
    - "8888:80"
  links:
    - influxdb

bansho:
  image: savoirfairelinux/bansho:0.4.0
  environment:
    BANSHO_BACKEND: "surveil"
    #BANSHO_SURVEIL_URL: "http://surveil:8080/"
    #BANSHO_AUTH_URL: "http://198.72.123.131:5000/v2.0/"
  ports:
    - "80:8888"
  links:
    - surveil
